#!/bin/sh
if [ -z "$PKEY" ]; then
# if PKEY is not specified, run ssh using default keyfile
ssh "$@"
else
ssh -i "$PKEY" ec2-user@"$@"
fi

# chmod +x this script
# we use ec2-user b/c our key file is linked to that.
